import Layout from '@/components/layout';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div className='flexmax-w-screen-lg'>
          <Layout />
          {children}
        </div>
      </body>
    </html>
  );
}
